### ISSUE TITLE
UTS | Dimas Nur

### ISSUE THREAD

**Issue by pipinfitriadi** [pipinfitriadi/pbo#36]
## Sistem Reservasi Hotel

Sebuah hotel ingin mengembangkan sistem reservasi sederhana untuk mengelola tamu, reservasi, dan kamar yang tersedia. Buatlah program Python yang menerapkan prinsip-prinsip dasar OOP, yaitu enkapsulasi, abstraksi, pewarisan, dan polimorfisme.

Spesifikasi:
1. Kelas Dasar:
   - Buat kelas `Person` yang memiliki atribut `nama` dan `nomor_telepon`. Kelas ini memiliki metode `tampilkan_info()` untuk menampilkan informasi dasar tamu.
2. Kelas Tamu:
   - Buat kelas `Tamu` yang merupakan turunan dari `Person`. Tambahkan atribut `id_tamu` dan `reservasi` (berisi daftar reservasi yang telah dibuat oleh tamu).
   - Buat metode `tambah_reservasi(reservasi)` untuk menambah reservasi ke daftar `reservasi`.
   - Override metode `tampilkan_info()` untuk menampilkan informasi khusus tamu.
3. Kelas Kamar:
   - Buat kelas `Kamar` dengan atribut `nomor_kamar`, `tipe_kamar` (misalnya: standar, deluxe, suite), dan `harga_per_malam`.
   - Implementasikan konsep enkapsulasi pada atribut dan buat metode tampilkan_info() untuk menampilkan informasi kamar.
4. Kelas Reservasi:
   - Buat kelas `Reservasi` yang memiliki atribut `id_reservasi`, `tamu`, `kamar`, `tanggal_check_in`, dan `tanggal_check_out`.
   - Tambahkan metode `hitung_total_harga()` untuk menghitung total harga berdasarkan lama menginap dan harga per malam.
5. Kelas SistemHotel:
   - Buat kelas `SistemHotel` yang memiliki metode untuk menambah dan menghapus tamu, kamar, serta mengelola reservasi.
   - Pastikan sistem hanya memperbolehkan reservasi jika kamar tersedia, dan tambahkan metode untuk menampilkan daftar kamar yang tersedia dan tamu yang terdaftar.

Instruksi:
   - Terapkan prinsip OOP yang sesuai pada setiap kelas, termasuk enkapsulasi dan polimorfisme.
   - Tambahkan komentar untuk menjelaskan penerapan pilar-pilar PBO.

**Comment by DimasNur30** [comment]
https://github.com/pipinfitriadi/pbo/pull/57

**Comment by DimasNur30** [comment]
https://urban-doodle-jr4qg9vwpw3p67v.github.dev/ revisi reservasi hotel
