### ISSUE TITLE
UTS | Aulia Rizky Ananda Siregar

### ISSUE THREAD

**Issue by pipinfitriadi** [pipinfitriadi/pbo#37]
## Sistem Manajemen Inventaris Toko

Sebuah toko ingin membuat sistem manajemen inventaris sederhana untuk mengelola produk dan transaksi penjualan. Buatlah program Python yang menerapkan konsep-konsep OOP.

Spesifikasi:
1. Kelas Produk:
   - Buat kelas `Produk` dengan atribut `id_produk`, `nama`, `kategori`, `harga`, dan `stok`.
   - Gunakan enkapsulasi pada atribut dan buat metode `tampilkan_info()` untuk menampilkan detail produk.
2. Kelas Transaksi:
   - Buat kelas `Transaksi` dengan atribut `id_transaksi`, `produk`, `jumlah`, dan `total_harga`.
   - Tambahkan metode `hitung_total_harga()` untuk menghitung total harga berdasarkan jumlah produk dan harga produk.
3. Kelas Kasir:
   - Buat kelas `Kasir` yang memiliki metode `tambah_produk(produk)`, `hapus_produk(produk)`, dan `proses_transaksi(transaksi)`. Metode `proses_transaksi()` akan mengurangi stok produk sesuai jumlah yang dijual dan menambahkan transaksi ke daftar transaksi.
   - Implementasikan polimorfisme dengan meng-override metode `tampilkan_info()` dari `Transaksi` untuk menampilkan ringkasan transaksi.
4. Kelas SistemInventaris:
   - Buat kelas `SistemInventaris` yang memiliki daftar produk dan transaksi, serta metode untuk menambah produk baru ke inventaris, menampilkan daftar produk, dan menampilkan daftar transaksi.

Instruksi:
   - Gunakan prinsip OOP secara efektif dalam desain kelas.
   - Tambahkan komentar yang menjelaskan penerapan prinsip OOP, terutama polimorfisme pada metode yang sesuai.

**Comment by auliarizkyananda13** [comment]
https://github.com/pipinfitriadi/pbo/pull/67
