### ISSUE TITLE
UTS | Na'ilah Salsabil Dalimunthe

### ISSUE THREAD

**Issue by pipinfitriadi** [pipinfitriadi/pbo#40]
## Sistem Manajemen Taman Bermain

Sebuah taman bermain ingin mengembangkan sistem sederhana untuk mengelola pengunjung, wahana, dan tiket. Buatlah program Python yang menerapkan konsep OOP.

Spesifikasi:
1. Kelas Pengunjung:
   - Buat kelas `Pengunjung` dengan atribut `nama`, `umur`, dan `id_pengunjung`.
   - Gunakan metode `tampilkan_info()` untuk menampilkan informasi pengunjung.
2. Kelas Wahana:
   - Buat kelas `Wahana` dengan atribut `nama_wahana`, `deskripsi`, dan `batas_umur`.
   - Gunakan metode `cek_batas_umur(pengunjung)` untuk memastikan pengunjung memenuhi batas umur untuk menaiki wahana tersebut.
   - Gunakan metode `tampilkan_info()` untuk menampilkan informasi wahana.
3. Kelas Tiket:
   - Buat kelas `Tiket` dengan atribut `id_tiket`, `pengunjung`, `wahana`, dan `tanggal`.
   - Gunakan metode `validasi_tiket()` untuk memastikan tiket valid berdasarkan umur pengunjung dan aturan wahana.
4. Kelas SistemTamanBermain:
   - Buat kelas `SistemTamanBermain` yang memiliki metode untuk menambah pengunjung, wahana, dan tiket.
   - Sistem harus memastikan tiket hanya dapat dipesan jika pengunjung memenuhi syarat batas umur wahana.

Instruksi:
   - Terapkan prinsip OOP termasuk enkapsulasi, abstraksi, pewarisan, dan polimorfisme.

**Comment by nailaahdlt** [comment]
https://github.com/pipinfitriadi/pbo/pull/60
