### ISSUE TITLE
UTS | Danur Cahya Agung

### ISSUE THREAD

**Issue by pipinfitriadi** [pipinfitriadi/pbo#41]
## Sistem Manajemen Proyek

Sebuah perusahaan ingin membuat sistem manajemen proyek sederhana untuk mengelola proyek, karyawan, dan tugas yang dikerjakan. Buatlah program Python yang menerapkan konsep-konsep OOP.

Spesifikasi:
1. Kelas Karyawan:
   - Buat kelas `Karyawan` dengan atribut `id_karyawan`, `nama`, dan `posisi`.
   - Gunakan metode `tampilkan_info()` untuk menampilkan informasi karyawan.
2. Kelas Proyek:
   - Buat kelas `Proyek` dengan atribut `nama_proyek`, `deskripsi`, `deadline`, dan `karyawan` (daftar karyawan yang terlibat).
   - Tambahkan metode `tambahkan_karyawan(karyawan)` untuk menambahkan karyawan ke proyek.
3. Kelas Tugas:
   - Buat kelas `Tugas` dengan atribut `id_tugas`, `deskripsi`, `proyek`, dan `status`.
   - Gunakan metode `ubah_status(status_baru)` untuk mengubah status tugas.
4. Kelas SistemManajemenProyek:
   - Buat kelas `SistemManajemenProyek` yang memiliki metode untuk menambah proyek, menambah tugas ke proyek, dan mengelola karyawan.

Instruksi:
   - Implementasikan enkapsulasi pada atribut dan gunakan polimorfisme pada metode `tampilkan_info()` di kelas `Karyawan` dan `Proyek`.

**Comment by danurcahya** [comment]
https://github.com/pipinfitriadi/pbo/pull/76
