### ISSUE TITLE
UTS | Siti Yulianti

### ISSUE THREAD

**Issue by pipinfitriadi** [pipinfitriadi/pbo#43]
## Sistem Pemesanan Tiket Bioskop

Sebuah bioskop ingin membuat sistem pemesanan tiket sederhana untuk mengelola film, penonton, dan tiket. Buatlah program Python yang menerapkan prinsip OOP.

Spesifikasi:
1. Kelas Film:
   - Buat kelas `Film` dengan atribut `judul`, `genre`, dan `durasi`.
   - Gunakan metode `tampilkan_info()` untuk menampilkan informasi film.
2. Kelas Penonton:
   - Buat kelas `Penonton` dengan atribut `nama`, `umur`, dan `id_penonton`.
   - Buat metode `cek_batas_umur(film)` untuk memastikan penonton sesuai dengan batas umur film (misalnya PG-13).
3. Kelas Tiket:
   - Buat kelas `Tiket` dengan atribut `id_tiket`, `film`, `penonton`, dan `waktu`.
   - Gunakan metode `validasi_tiket()` untuk memvalidasi tiket berdasarkan batas umur.
4. Kelas SistemBioskop:
   - Buat kelas `SistemBioskop` yang memiliki metode untuk menambah film, menambah penonton, dan membuat tiket pemesanan.
   - Pastikan sistem hanya memperbolehkan pemesanan tiket jika penonton sesuai dengan batas umur film.

Instruksi:
   - Terapkan prinsip OOP seperti enkapsulasi dan polimorfisme pada kelas dan metode yang relevan.

**Comment by siti-yl** [comment]
https://github.com/siti-yl/pbo/blob/main/uts.py

**Comment by siti-yl** [comment]
[#74 ](https://cautious-space-disco-pjpp47vv9qgj275jr.github.dev)

**Comment by siti-yl** [comment]
[#74](https://humble-space-guide-7vpp67qqwx47frgv.github.dev)

**Comment by siti-yl** [comment]
#74
