### ISSUE TITLE
UTS | Mahesa Safta Lingga Saputra

### ISSUE THREAD

**Issue by pipinfitriadi** [pipinfitriadi/pbo#44]
## Sistem Pengelolaan Gudang

Sebuah gudang besar ingin membuat sistem pengelolaan stok barang, supplier, dan transaksi masuk-keluar barang. Buatlah program Python yang menerapkan konsep-konsep OOP.

Spesifikasi:
1. Kelas Barang:
   - Buat kelas `Barang` dengan atribut `id_barang`, `nama`, `kategori`, dan `stok`.
   - Gunakan metode `tambah_stok(jumlah)` dan `kurangi_stok(jumlah)` untuk mengatur stok barang.
2. Kelas Supplier:
   - Buat kelas `Supplier` dengan atribut `nama`, `kontak`, dan `daftar_barang` yang disuplai.
   - Gunakan metode `tampilkan_info()` untuk menampilkan informasi supplier.
3. Kelas Transaksi:
   - Buat kelas `Transaksi` dengan atribut `id_transaksi`, `barang`, `jumlah`, dan `tipe` (masuk atau keluar).
   - Gunakan metode `proses_transaksi()` untuk menambah atau mengurangi stok barang.
4. Kelas SistemGudang:
   - Buat kelas `SistemGudang` yang memiliki metode untuk menambah barang, menambah supplier, dan mengelola transaksi masuk-keluar barang.
   - Sistem harus memastikan stok barang tidak negatif setelah transaksi keluar.

Instruksi:
   - Gunakan prinsip OOP termasuk enkapsulasi, pewarisan, abstraksi, dan polimorfisme pada kelas dan metode yang relevan.

**Comment by MahesaSaftaLinggaS** [comment]
https://github.com/pipinfitriadi/pbo/pull/59
