### ISSUE TITLE
UTS | Muhammad Ridho Masykur

### ISSUE THREAD

**Issue by pipinfitriadi** [pipinfitriadi/pbo#45]
## Sistem Pemesanan Tiket Pesawat

Sebuah maskapai penerbangan ingin mengembangkan sistem pemesanan tiket pesawat yang sederhana untuk mengelola penumpang, penerbangan, dan tiket. Buatlah program Python yang menerapkan konsep-konsep OOP.

Spesifikasi:
1. Kelas Penumpang:
   - Buat kelas `Penumpang` dengan atribut `nama`, `nomor_paspor`, dan `tanggal_lahir`.
   - Buat metode `cek_umur()` untuk menghitung umur penumpang berdasarkan tanggal lahir.
2. Kelas Penerbangan:
   - Buat kelas `Penerbangan` dengan atribut `nomor_penerbangan`, `asal`, `tujuan`, dan `jadwal_berangkat`.
   - Tambahkan metode `tampilkan_info()` untuk menampilkan informasi penerbangan.
3. Kelas TiketPesawat:
   - Buat kelas `TiketPesawat` dengan atribut `id_tiket`, `penumpang`, `penerbangan`, dan `nomor_kursi`.
   - Tambahkan metode `validasi_tiket()` untuk memastikan tiket valid.
4. Kelas SistemPemesananTiket:
   - Buat kelas `SistemPemesananTiket` yang memiliki metode untuk menambah penumpang, menambah penerbangan, dan memesan tiket.
   - Pastikan sistem menolak pemesanan jika penerbangan sudah penuh.

Instruksi:
   - Terapkan prinsip OOP seperti pewarisan, polimorfisme, dan enkapsulasi pada kelas dan metode yang relevan.

**Comment by Ridho4734** [comment]
https://github.com/pipinfitriadi/pbo/pull/75
