### ISSUE TITLE
UTS | Ali Albuni

### ISSUE THREAD

**Issue by pipinfitriadi** [pipinfitriadi/pbo#46]
## Sistem Manajemen Perpustakaan Digital

Sebuah perpustakaan digital ingin mengembangkan sistem sederhana untuk mengelola buku, anggota, dan peminjaman. Buatlah program Python yang menerapkan konsep-konsep OOP.

Spesifikasi:
1. Kelas Buku:
   - Buat kelas `Buku` dengan atribut `isbn`, `judul`, `pengarang`, dan `jumlah_eksemplar`.
   - Tambahkan metode `tampilkan_info()` untuk menampilkan informasi buku.
2. Kelas Anggota:
   - Buat kelas `Anggota` dengan atribut `id_anggota`, `nama`, dan `buku_dipinjam` (daftar buku yang dipinjam anggota).
   - Buat metode `pinjam_buku(buku)` dan `kembalikan_buku(buku)` untuk mengatur peminjaman dan pengembalian buku.
3. Kelas Peminjaman:
   - Buat kelas `Peminjaman` dengan atribut `id_peminjaman`, `anggota`, `buku`, dan `tanggal_peminjaman`.
   - Tambahkan metode `cek_keterlambatan()` untuk menghitung keterlambatan pengembalian buku.
4. Kelas SistemPerpustakaan:
   - Buat kelas `SistemPerpustakaan` yang memiliki metode untuk menambah buku, menambah anggota, dan mengelola peminjaman.
   - Sistem harus memastikan anggota tidak dapat meminjam buku jika tidak ada eksemplar yang tersedia.

Instruksi:
   - Gunakan prinsip OOP seperti pewarisan, enkapsulasi, dan polimorfisme pada kelas dan metode yang relevan.

**Comment by alialbuni623** [comment]
https://github.com/pipinfitriadi/pbo/pull/61
