### ISSUE TITLE
UTS | Nissy Auliyanti Shalehah

### ISSUE THREAD

**Issue by pipinfitriadi** [pipinfitriadi/pbo#47]
## Sistem Manajemen Layanan Kesehatan

Sebuah klinik kesehatan ingin mengembangkan sistem sederhana untuk mengelola pasien, dokter, dan janji temu. Buatlah program Python yang menggunakan konsep OOP.

Spesifikasi:
1. Kelas Pasien:
   - Buat kelas `Pasien` dengan atribut `nama`, `nomor_identitas`, dan `usia`.
   - Tambahkan metode `tampilkan_info()` untuk menampilkan informasi pasien.
2. Kelas Dokter:
   - Buat kelas `Dokter` dengan atribut `nama`, `spesialisasi`, dan `jadwal` (daftar jadwal janji temu yang dipegang).
   - Tambahkan metode `tambah_jadwal(janji_temu)` untuk menambah jadwal janji temu.
3. Kelas JanjiTemu:
   - Buat kelas `JanjiTemu` dengan atribut `id_janji`, `pasien`, `dokter`, dan `waktu`.
   - Tambahkan metode `konfirmasi_janji()` untuk memastikan janji temu dapat dilakukan sesuai jadwal dokter.
4. Kelas SistemKlinik:
   - Buat kelas `SistemKlinik` yang memiliki metode untuk menambah pasien, menambah dokter, dan mengatur janji temu.
   - Sistem harus memastikan tidak ada tumpang tindih waktu pada janji temu dokter.

Instruksi:
   - Gunakan prinsip OOP seperti enkapsulasi, pewarisan, dan polimorfisme pada kelas dan metode yang relevan.

**Comment by nissyauliyantis** [comment]
https://potential-train-r4ppq7q96vp7hg95.github.dev/

**Comment by nissyauliyantis** [comment]
https://ubiquitous-train-q7ppjvjr4xx739gww.github.dev/

**Comment by nissyauliyantis** [comment]
https://github.com/pipinfitriadi/pbo/pull/68/files

**Comment by nissyauliyantis** [comment]
[https://glowing-space-journey-r4ppq7q9697jcjg.github.dev/](#68)
