### ISSUE TITLE
UTS | Muhammad Zaid Anwar

### ISSUE THREAD

**Issue by pipinfitriadi** [pipinfitriadi/pbo#48]
## Sistem Pengelolaan Sewa Kendaraan

Sebuah perusahaan rental kendaraan ingin membuat sistem pengelolaan untuk menyewakan kendaraan kepada pelanggan. Buatlah program Python yang menerapkan prinsip OOP.

Spesifikasi:
1. Kelas Pelanggan:
   - Buat kelas `Pelanggan` dengan atribut `nama`, `nomor_identitas`, dan `umur`.
   - Gunakan metode `tampilkan_info()` untuk menampilkan informasi pelanggan.
2. Kelas Kendaraan:
   - Buat kelas `Kendaraan` dengan atribut `nomor_polisi`, `tipe`, `harga_per_hari`, dan `status` (tersedia atau disewa).
   - Tambahkan metode `ubah_status()` untuk mengubah status kendaraan menjadi disewa atau tersedia.
3. Kelas Sewa:
   - Buat kelas `Sewa` dengan atribut `id_sewa`, `pelanggan`, `kendaraan`, `tanggal_mulai`, dan `tanggal_akhir`.
   - Tambahkan metode `hitung_biaya()` untuk menghitung total biaya sewa berdasarkan durasi sewa dan harga per hari.
4. Kelas SistemRental:
   - Buat kelas `SistemRental` yang memiliki metode untuk menambah pelanggan, menambah kendaraan, dan mengelola sewa.
   - Sistem harus memastikan kendaraan hanya bisa disewa jika statusnya tersedia.

Instruksi:
   - Gunakan prinsip OOP seperti enkapsulasi, pewarisan, dan polimorfisme pada kelas dan metode yang relevan.

**Comment by AnwarZaid** [comment]
https://curly-space-parakeet-x5vv7r7jgpw9hv9jq.github.dev

**Comment by AnwarZaid** [comment]
https://github.com/pipinfitriadi/pbo/pull/69
