### ISSUE TITLE
UTS | Tantra Mulya Nugraha

### ISSUE THREAD

**Issue by pipinfitriadi** [pipinfitriadi/pbo#49]
## Sistem Pengelolaan Proyek Konstruksi

Sebuah perusahaan konstruksi ingin membuat sistem untuk mengelola proyek, pekerja, dan tugas dalam setiap proyek. Buatlah program Python yang menerapkan konsep-konsep OOP.

Spesifikasi:
1. Kelas Pekerja:
   - Buat kelas `Pekerja` dengan atribut `id_pekerja`, `nama`, `posisi`, dan `gaji_per_jam`.
   - Gunakan metode `hitung_gaji(jam_kerja)` untuk menghitung total gaji berdasarkan jam kerja.
2. Kelas Proyek:
   - Buat kelas `Proyek` dengan atribut `nama_proyek`, `lokasi`, `deadline`, dan `pekerja` (daftar pekerja yang terlibat).
   - Tambahkan metode `tambahkan_pekerja(pekerja)` untuk menambahkan pekerja ke proyek.
3. Kelas Tugas:
   - Buat kelas `Tugas` dengan atribut `id_tugas`, `deskripsi`, `status`, dan `proyek`.
   - Gunakan metode `ubah_status(status_baru)` untuk mengubah status tugas.
4. Kelas SistemManajemenKonstruksi:
   - Buat kelas `SistemManajemenKonstruksi` yang memiliki metode untuk menambah proyek, menambah pekerja, dan mengelola tugas.
   - Sistem harus memastikan hanya pekerja yang terdaftar di proyek yang dapat ditugaskan ke tugas tersebut.

Instruksi:
   - Gunakan prinsip OOP seperti pewarisan, enkapsulasi, dan polimorfisme pada kelas dan metode yang relevan.

**Comment by Tantra04** [comment]
https://curly-halibut-wrggpv6r6rqv35r7g.github.dev/

**Comment by Tantra04** [comment]
https://fuzzy-waddle-6944qv6965gj2rrg4.github.dev/

**Comment by Tantra04** [comment]
https://github.com/pipinfitriadi/pbo/pull/66
