### ISSUE TITLE
UTS | Annisa Ramadhani Putri

### ISSUE THREAD

**Issue by pipinfitriadi** [pipinfitriadi/pbo#50]
## Sistem Manajemen Inventaris Kantor

Sebuah perusahaan ingin mengelola inventaris kantor yang mencakup berbagai peralatan dan kebutuhan kantor. Buatlah program Python yang menerapkan konsep-konsep OOP.

Spesifikasi:
1. Kelas BarangInventaris:
   - Buat kelas `BarangInventaris` dengan atribut `id_barang`, `nama_barang`, `kategori`, `jumlah`, dan `kondisi` (baik, rusak).
   - Buat metode `tampilkan_info()` untuk menampilkan informasi barang.
2. Kelas Karyawan:
   - Buat kelas `Karyawan` dengan atribut `id_karyawan`, `nama`, dan `jabatan`.
   - Gunakan metode `tampilkan_info()` untuk menampilkan informasi karyawan.
3. Kelas PeminjamanInventaris:
   - Buat kelas `PeminjamanInventaris` dengan atribut `id_peminjaman`, `karyawan`, `barang`, `tanggal_pinjam`, dan `tanggal_kembali`.
   - Tambahkan metode `validasi_pengembalian()` untuk memeriksa apakah barang sudah dikembalikan atau belum.
4. Kelas SistemInventaris:
   - Buat kelas `SistemInventaris` yang memiliki metode untuk menambah barang, menambah karyawan, dan mencatat peminjaman inventaris.
   - Sistem harus memastikan jumlah barang cukup sebelum dapat dipinjam oleh karyawan.

Instruksi:
   - Terapkan prinsip OOP seperti enkapsulasi, pewarisan, dan polimorfisme pada kelas dan metode yang relevan.

**Comment by annisaputri29** [comment]
https://fantastic-fishstick-6944qvjr554wfr6xg.github.dev/

**Comment by annisaputri29** [comment]
https://symmetrical-happiness-7vpp67gr56pjfwp5j.github.dev/
