### ISSUE TITLE
UTS | Novi Miftah Hanif

### ISSUE THREAD

**Issue by pipinfitriadi** [pipinfitriadi/pbo#51]
## Sistem Pengelolaan Pelatihan Karyawan

Sebuah perusahaan ingin membuat sistem untuk mengelola pelatihan karyawan yang mencakup berbagai pelatihan dan instruktur. Buatlah program Python yang menerapkan prinsip OOP.

Spesifikasi:
1. Kelas Karyawan:
   - Buat kelas `Karyawan` dengan atribut `id_karyawan`, `nama`, dan `departemen`.
   - Buat metode `tampilkan_info()` untuk menampilkan informasi karyawan.
2. Kelas Pelatihan:
   - Buat kelas `Pelatihan` dengan atribut `id_pelatihan`, `nama_pelatihan`, `deskripsi`, dan `instruktur`.
   - Gunakan metode `tampilkan_info()` untuk menampilkan informasi pelatihan.
3. Kelas Instruktur:
   - Buat kelas `Instruktur` dengan atribut `id_instruktur`, `nama`, dan `keahlian`.
   - Tambahkan metode `tampilkan_info()` untuk menampilkan informasi instruktur.
4. Kelas SistemPelatihan:
   - Buat kelas `SistemPelatihan` yang memiliki metode untuk menambah karyawan, menambah pelatihan, dan mendaftarkan karyawan ke pelatihan tertentu.
   - Pastikan sistem hanya memungkinkan karyawan untuk mendaftar pada pelatihan yang relevan dengan departemennya.

Instruksi:
   - Gunakan prinsip OOP seperti pewarisan, polimorfisme, dan enkapsulasi pada kelas dan metode yang relevan.

**Comment by miftahhaniF** [comment]
https://reimagined-dollop-jjqqvr6xxw96f54wq.github.dev/
