### ISSUE TITLE
UTS | Imam Bariq Ibrahim

### ISSUE THREAD

**Issue by pipinfitriadi** [pipinfitriadi/pbo#52]
## Sistem Manajemen Event

Sebuah perusahaan event organizer ingin mengembangkan sistem untuk mengelola event, peserta, dan jadwal kegiatan. Buatlah program Python yang menerapkan konsep-konsep OOP.

Spesifikasi:
1. Kelas Peserta:
   - Buat kelas `Peserta` dengan atribut `id_peserta`, `nama`, dan `jenis_tiket`.
   - Buat metode `tampilkan_info()` untuk menampilkan informasi peserta.
2. Kelas Event:
   - Buat kelas `Event` dengan atribut `nama_event`, `lokasi`, dan `tanggal`.
   - Gunakan metode `tampilkan_info()` untuk menampilkan informasi event.
3. Kelas Kegiatan:
   - Buat kelas `Kegiatan` dengan atribut `id_kegiatan`, `nama_kegiatan`, `jadwal`, dan `event`.
   - Tambahkan metode `ubah_jadwal(jadwal_baru)` untuk mengubah jadwal kegiatan.
4. Kelas SistemEvent:
   - Buat kelas `SistemEvent` yang memiliki metode untuk menambah peserta, menambah event, dan mengelola kegiatan dalam event.
   - Sistem harus memastikan tidak ada tumpang tindih waktu pada jadwal kegiatan dalam satu event.

Instruksi:
   - Gunakan prinsip OOP seperti enkapsulasi, pewarisan, dan polimorfisme pada kelas dan metode yang relevan.

**Comment by imambariq26** [comment]
https://github.com/pipinfitriadi/pbo/pull/65

**Comment by imambariq26** [comment]
https://super-space-train-v6qq9p49gvx6cp96v.github.dev/
