### ISSUE TITLE
UTS | Daniswara Aryaguna

### ISSUE THREAD

**Issue by pipinfitriadi** [pipinfitriadi/pbo#53]
## Sistem Manajemen Portofolio Investasi

Sebuah perusahaan manajemen keuangan ingin mengembangkan sistem untuk mengelola portofolio investasi, investor, dan aset. Buatlah program Python yang menerapkan prinsip-prinsip OOP.

Spesifikasi:
1. Kelas Investor:
   - Buat kelas `Investor` dengan atribut `id_investor`, `nama`, dan `saldo`.
   - Buat metode `tampilkan_info()` untuk menampilkan informasi investor.
2. Kelas Aset:
   - Buat kelas `Aset` dengan atribut `id_aset`, `nama_aset`, `jenis_aset` (saham, obligasi, dll.), dan `nilai`.
   - Tambahkan metode `ubah_nilai(nilai_baru)` untuk mengubah nilai aset.
3. Kelas Portofolio:
   - Buat kelas `Portofolio` dengan atribut `id_portofolio`, `investor`, dan `daftar_aset` (daftar aset yang dimiliki).
   - Gunakan metode `tambah_aset(aset)` untuk menambah aset ke dalam portofolio.
4. Kelas SistemInvestasi:
   - Buat kelas `SistemInvestasi` yang memiliki metode untuk menambah investor, menambah aset, dan mengelola portofolio investasi.
   - Sistem harus memastikan investor memiliki saldo yang cukup sebelum membeli aset.

Instruksi:
   - Terapkan prinsip OOP seperti enkapsulasi, pewarisan, dan polimorfisme pada kelas dan metode yang relevan.

**Comment by Arrss111** [comment]
https://github.com/pipinfitriadi/pbo/pull/58
