### ISSUE TITLE
UTS | Bunga Ananda Fricellia

### ISSUE THREAD

**Issue by pipinfitriadi** [pipinfitriadi/pbo#55]
## Sistem Manajemen Donasi Amal

Sebuah lembaga amal ingin membuat sistem untuk mengelola donasi, donatur, dan kampanye amal yang sedang berlangsung. Buatlah program Python yang menerapkan konsep-konsep OOP.

Spesifikasi:
1. Kelas Donatur:
   - Buat kelas `Donatur` dengan atribut `id_donatur`, `nama`, dan `email`.
   - Buat metode `tampilkan_info()` untuk menampilkan informasi donatur.
2. Kelas KampanyeAmal:
   - Buat kelas `KampanyeAmal` dengan atribut `id_kampanye`, `nama_kampanye`, `target_donasi`, dan `total_terkumpul`.
   - Tambahkan metode `tambah_donasi(jumlah)` untuk menambahkan donasi ke total terkumpul.
3. Kelas Donasi:
   - Buat kelas `Donasi` dengan atribut `id_donasi`, `donatur`, `kampanye`, dan `jumlah`.
   - Buat metode `validasi_donasi()` untuk memastikan donasi valid (jumlah lebih dari 0).
4. Kelas SistemDonasi:
   - Buat kelas `SistemDonasi` yang memiliki metode untuk menambah donatur, menambah kampanye amal, dan mencatat donasi.
   - Sistem harus memastikan kampanye tidak melebihi target donasi yang telah ditetapkan.

Instruksi:
   - Terapkan prinsip OOP seperti enkapsulasi, pewarisan, dan polimorfisme pada kelas dan metode yang relevan.

**Comment by Bunga-ananda** [comment]
https://organic-umbrella-5gxxjv65r6qv2x6v.github.dev/

**Comment by Bunga-ananda** [comment]
[#62 ](https://organic-umbrella-5gxxjv65r6qv2x6v.github.dev/)

**Comment by Bunga-ananda** [comment]
#62
