### ISSUE TITLE
UTS | Nabya Zahira Putri Ruchyandi

### ISSUE THREAD

**Issue by pipinfitriadi** [pipinfitriadi/pbo#56]
## Sistem Manajemen Kursus Online

Sebuah platform edukasi ingin mengembangkan sistem sederhana untuk mengelola kursus, instruktur, dan pendaftaran siswa. Buatlah program Python yang menerapkan prinsip-prinsip OOP.

Spesifikasi:
1. Kelas Siswa:
   - Buat kelas `Siswa` dengan atribut `id_siswa`, `nama`, dan `email`.
   - Gunakan metode `tampilkan_info()` untuk menampilkan informasi siswa.
2. Kelas Instruktur:
   - Buat kelas `Instruktur` dengan atribut `id_instruktur`, `nama`, dan `keahlian`.
   - Tambahkan metode `tampilkan_info()` untuk menampilkan informasi instruktur.
3. Kelas Kursus:
   - Buat kelas `Kursus` dengan atribut `id_kursus`, `nama_kursus`, `deskripsi`, `instruktur`, dan `jumlah_pendaftar`.
   - Tambahkan metode `tambah_siswa(siswa)` untuk menambahkan siswa yang mendaftar ke kursus.
4. Kelas SistemKursus:
   - Buat kelas `SistemKursus` yang memiliki metode untuk menambah siswa, menambah instruktur, dan mengelola pendaftaran kursus.
   - Sistem harus memastikan kursus tidak bisa menerima lebih dari kapasitas maksimum pendaftar.

Instruksi:
   - Gunakan prinsip OOP seperti pewarisan, polimorfisme, dan enkapsulasi pada kelas dan metode yang relevan.

**Comment by nabyazahiraa** [comment]
https://ideal-spoon-r4ppq79pgwg4cpvr.github.dev/
